#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
OUT_FILE="$REPO_ROOT/docs/capacity_dataset_manifest.md"
TMP_FILE="$OUT_FILE.tmp"

if ! command -v sha256sum >/dev/null 2>&1; then
  echo "sha256sum is required but was not found" >&2
  exit 1
fi

cd "$REPO_ROOT"
mkdir -p "$REPO_ROOT/docs"

GIT_COMMIT="unknown"
GIT_TAG="none"
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || printf '%s' "unknown")
  GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || printf '%s' "none")
fi

FILES=$(find reports/capacity -type f -name '*.json' 2>/dev/null | LC_ALL=C sort || true)

{
  printf '# Capacity Dataset Manifest\n\n'
  printf 'Generated by `scripts/make_capacity_manifest.sh`.\n\n'
  printf '%s\n' "- git commit: \`$GIT_COMMIT\`"
  printf '%s\n\n' "- git tag: \`$GIT_TAG\`"
  printf '| path | bytes | sha256 |\n'
  printf '| --- | ---: | --- |\n'

  if [ -n "$FILES" ]; then
    printf '%s\n' "$FILES" | while IFS= read -r file; do
      bytes=$(wc -c < "$file" | tr -d '[:space:]')
      sha=$(sha256sum "$file" | awk '{print $1}')
      printf '| `%s` | %s | `%s` |\n' "$file" "$bytes" "$sha"
    done
  else
    printf '| _none_ | 0 | `n/a` |\n'
  fi
} > "$TMP_FILE"

mv "$TMP_FILE" "$OUT_FILE"
echo "Wrote $OUT_FILE"
